"""
site-overrides.py — apply per-site fixes saved by qute-ai-fix.

Sourced by config.py via: config.source('site-overrides.py')

qute-ai-fix stores one JSON file per domain under
    $XDG_STATE_HOME/omarchy-qutebrowser/site-fixes/<domain>.json

qutebrowser's content.user_stylesheets is GLOBAL — it has no per-domain
patterns — so applying every domain's rules through one stylesheet would leak
a fix for one site onto every other site. Instead this module writes one
per-domain Greasemonkey script per fix file; each script is @match'd to its own
domain, so a fix can never leak. Generated scripts live at
    $XDG_DATA_HOME/qutebrowser/greasemonkey/omarchy-sitefix-<domain>.js
and are removed again when their fix file disappears. Because config is sourced
before qutebrowser's Greasemonkey manager starts, the scripts are loaded at
startup; a running instance is refreshed by `:greasemonkey-reload`.

Keys read from each JSON file:
    css_hide       [selector, ...]     hidden with display:none !important
    css_override   ["rule;", ...]      injected verbatim
    adblock_rules  [cosmetic filter]   reduced to their CSS selector and hidden
"""

import json
import os
import pathlib
import sys

MARKER = "omarchy-sitefix-"


def _state_dir() -> pathlib.Path:
    base = os.environ.get("XDG_STATE_HOME") or str(pathlib.Path.home() / ".local/state")
    return pathlib.Path(base) / "omarchy-qutebrowser" / "site-fixes"


def _greasemonkey_dir() -> pathlib.Path:
    base = os.environ.get("XDG_DATA_HOME") or str(pathlib.Path.home() / ".local/share")
    return pathlib.Path(base) / "qutebrowser" / "greasemonkey"


def _cosmetic_selectors(adblock_rules) -> list:
    """Reduce uBlock/EasyList cosmetic rules to plain CSS selectors.

    Handles `domain##selector` and `##selector`. Network rules (`||...`,
    `@@...`, `/regex/`, anything containing `$`) cannot be expressed as CSS
    and are dropped, as are rules using unsupported *procedural* pseudos
    (`:has-text()`, `:matches-css()`, `:style()`, `-abp-...`) which are not
    valid CSS and would poison a stylesheet.
    """
    procedural = (":has-text(", ":matches-css(", ":style(", ":remove(", "-abp-", ":-abp-")
    selectors = []
    for rule in adblock_rules or []:
        if not isinstance(rule, str):
            continue
        rule = rule.strip()
        if not rule or "$" in rule:
            continue
        if rule.startswith(("||", "@@", "/", "#@", "#$#", "#@#", "#?#")):
            continue
        if "##" in rule:
            rule = rule.split("##", 1)[1].strip()
        if any(tok in rule for tok in procedural):
            continue
        if rule:
            selectors.append(rule)
    return selectors


def _build_css(fixes) -> str:
    parts = []

    hide = list(fixes.get("css_hide") or []) + _cosmetic_selectors(fixes.get("adblock_rules"))
    # Emit one rule PER selector: a single invalid selector in a comma-joined
    # list would invalidate the whole rule and silently drop every other hide.
    for selector in hide:
        if isinstance(selector, str) and selector.strip():
            parts.append("%s { display: none !important; visibility: hidden !important; }"
                         % selector.strip())

    for rule in fixes.get("css_override") or []:
        if isinstance(rule, str) and rule.strip():
            parts.append(rule.strip())

    return "\n".join(parts)


def _script_for(domain: str, css: str) -> str:
    host = domain.split(":", 1)[0]  # strip any :port for the @match patterns
    matches = [f"// @match        *://{host}/*"]
    if not host.startswith("*."):
        matches.append(f"// @match        *://*.{host}/*")
    css_json = json.dumps(css)
    return "\n".join([
        "// ==UserScript==",
        f"// @name         omarchy site fix: {domain}",
        "// @description  Auto-generated by omarchy-qutebrowser (qute-ai-fix). Do not edit by hand.",
        "// @namespace    https://github.com/Maximilian-Maag/omarchy-qutebrowser",
        "// @version      1",
        *matches,
        "// @run-at       document-start",
        "// @grant        none",
        "// ==/UserScript==",
        "",
        "(function () {",
        "  'use strict';",
        f"  var css = {css_json};",
        "  function inject() {",
        "    try {",
        "      var style = document.createElement('style');",
        "      style.id = 'omarchy-site-fixes';",
        "      style.textContent = css;",
        "      (document.head || document.documentElement).appendChild(style);",
        "    } catch (e) {}",
        "  }",
        "  if (document.head) { inject(); }",
        "  else { document.addEventListener('DOMContentLoaded', inject); }",
        "})();",
        "",
    ])


def _remove_stale(gm_dir: pathlib.Path, keep: set) -> None:
    if not gm_dir.exists():
        return
    for script in gm_dir.glob(f"{MARKER}*.js"):
        if script.name not in keep:
            try:
                script.unlink()
            except OSError:
                pass


def _apply_site_fixes() -> None:
    """Regenerate per-domain Greasemonkey scripts from the saved fix files."""
    state_dir = _state_dir()
    gm_dir = _greasemonkey_dir()

    if not state_dir.exists():
        _remove_stale(gm_dir, set())
        return

    gm_dir.mkdir(parents=True, exist_ok=True)

    keep = set()
    for fix_file in sorted(state_dir.glob("*.json")):
        domain = fix_file.stem
        try:
            fixes = json.loads(fix_file.read_text())
        except (OSError, ValueError):
            continue
        if not isinstance(fixes, dict):
            continue
        css = _build_css(fixes)
        if not css:
            continue
        dest = gm_dir / f"{MARKER}{domain}.js"
        dest.write_text(_script_for(domain, css))
        keep.add(dest.name)

    _remove_stale(gm_dir, keep)


try:
    _apply_site_fixes()
except Exception as exc:  # noqa: BLE001 - never take the whole config down for a fix
    print(f"omarchy-qutebrowser: site-overrides failed: {exc}", file=sys.stderr)
