"""
site-overrides.py — auto-generated per-site fixes from qute-ai-fix
This file is sourced by config.py via: config.source('site-overrides.py')

For each domain that has a saved fix, this file:
1. Injects the fix data as window.__omarchyFixes via content.javascript.extra_urls
   (so site-fixes.js Greasemonkey script can read and apply CSS/JS fixes)
2. Sets content.javascript.enabled = True for domains where AI determined JS was blocked
3. Applies user stylesheet overrides via content.user_stylesheets

This file is regenerated by qute-ai-fix-update (run at startup via autostart hook).
DO NOT edit by hand — run: spawn --userscript qute-ai-fix to add fixes for a site.
"""

import os
import json
import pathlib

_STATE_DIR = pathlib.Path(
    os.environ.get("XDG_STATE_HOME", str(pathlib.Path.home() / ".local/state"))
) / "omarchy-qutebrowser" / "site-fixes"

def _apply_site_fixes(c):  # noqa: F821
    """Read all saved domain fix files and apply them to qutebrowser config."""
    if not _STATE_DIR.exists():
        return

    css_rules = []  # collected for user stylesheet

    for fix_file in _STATE_DIR.glob("*.json"):
        domain = fix_file.stem
        try:
            fixes = json.loads(fix_file.read_text())
        except Exception:
            continue

        url_pattern = f"*://{domain}/*"

        # 1. JS allow
        if fixes.get("js_allow"):
            config.set("content.javascript.enabled", True, url_pattern)  # noqa

        # 2. Inject fix data as window.__omarchyFixes so site-fixes.js can apply CSS
        css_hide    = fixes.get("css_hide", [])
        css_override = fixes.get("css_override", [])

        if css_hide or css_override:
            fix_json = json.dumps({"css_hide": css_hide, "css_override": css_override})
            # Escape for JS string literal
            fix_json_escaped = fix_json.replace("\\", "\\\\").replace("'", "\\'")
            js_inject = (
                f"(function(){{"
                f"try{{window.__omarchyFixes=JSON.parse('{fix_json_escaped}');}}catch(e){{}}"
                f"}})();"
            )
            config.set(  # noqa
                "content.javascript.extra_urls",
                [f"javascript:{js_inject}"],
                url_pattern,
            )

            # Also add to user stylesheet for pre-JS-load hiding
            if css_hide:
                css_rules.append(
                    f"/* {domain} — qute-ai-fix */\n"
                    + ",\n".join(css_hide)
                    + " { display: none !important; visibility: hidden !important; }"
                )
            if css_override:
                css_rules.append(f"/* {domain} overrides */\n" + "\n".join(css_override))

    # 3. Write combined user stylesheet
    if css_rules:
        stylesheet_path = pathlib.Path(
            os.environ.get("XDG_CONFIG_HOME", str(pathlib.Path.home() / ".config"))
        ) / "qutebrowser" / "site-fixes.css"
        stylesheet_path.write_text("\n\n".join(css_rules) + "\n")
        c.content.user_stylesheets = [str(stylesheet_path)]  # noqa

try:
    _apply_site_fixes(c)  # noqa: F821  (c injected by qutebrowser)
except Exception:
    pass
